import { afterEach,describe,expect,it,vi } from 'vitest'
import { OptionalResearchProvider,type ResearchProvider } from '../research/tavily'
import { NewRelicTelemetryAdapter } from './newrelic'
afterEach(()=>vi.unstubAllGlobals())
const config={userKey:'user-key',accountId:123,region:'US' as const,fleetPrefix:'avmos-node-'}
const response=(results:unknown[])=>Response.json({data:{actor:{account:{nrql:{results}}}}})
const host='avmos-node-01'
describe('New Relic fleet telemetry',()=>{
  it('normalizes multiple AVMOS hosts and excludes unrelated inventory',async()=>{const now=Date.now();vi.stubGlobal('fetch',vi.fn<typeof fetch>().mockResolvedValueOnce(response([{cpu:22,memory:61,observedAt:now,facet:host},{cpu:10,memory:20,observedAt:now,facet:'avmos-node-02'},{cpu:1,memory:1,observedAt:now,facet:'server1'}])).mockResolvedValueOnce(response([{utilization:81,totalBytes:1000,usedBytes:810,observedAt:now,facet:[host,'/']},{utilization:20,observedAt:now,facet:['avmos-node-02','/']}])).mockResolvedValueOnce(response([{received:100,transmitted:50,observedAt:now,facet:[host,'eth0']},{received:25,transmitted:10,observedAt:now,facet:['avmos-node-02','eth0']}])));const fleet=await new NewRelicTelemetryAdapter(config).getFleetSnapshots();expect(fleet.map(item=>item.resource.id)).toEqual(['avmos-node-01','avmos-node-02']);expect(fleet[0].resource.metrics).toMatchObject({cpuUtilization:22,memoryUtilization:61,storageUtilization:81,networkReceiveBytesPerSecond:100})})
  it('marks missing metrics unavailable instead of displaying zero',async()=>{const now=Date.now();vi.stubGlobal('fetch',vi.fn<typeof fetch>().mockResolvedValueOnce(response([{observedAt:now,facet:host}])).mockResolvedValueOnce(response([])).mockResolvedValueOnce(response([])));const snapshot=await new NewRelicTelemetryAdapter(config).getSnapshot(host);expect(snapshot.observations.every(item=>item.status==='UNAVAILABLE')).toBe(true);expect(snapshot.resource.metrics).not.toHaveProperty('storageUtilization');expect(snapshot.resource.status).toBe('offline')})
  it('marks a failed provider query as error while retaining successful metric groups',async()=>{const now=Date.now();vi.stubGlobal('fetch',vi.fn<typeof fetch>().mockResolvedValueOnce(response([{cpu:22,memory:61,observedAt:now,facet:host}])).mockRejectedValueOnce(new Error('storage failed')).mockResolvedValueOnce(response([{received:100,transmitted:50,observedAt:now,facet:[host,'eth0']}])));const snapshot=await new NewRelicTelemetryAdapter(config).getSnapshot(host);expect(snapshot.observations.find(item=>item.metric==='storage_utilization')?.status).toBe('ERROR');expect(snapshot.observations.find(item=>item.metric==='cpu_utilization')?.status).toBe('LIVE')})
  it('marks stale samples without turning them healthy',async()=>{const old=Date.now()-180_000;vi.stubGlobal('fetch',vi.fn<typeof fetch>().mockResolvedValueOnce(response([{cpu:5,memory:5,observedAt:old,facet:host}])).mockResolvedValueOnce(response([{utilization:5,observedAt:old,facet:[host,'/']}])).mockResolvedValueOnce(response([{received:1,transmitted:1,observedAt:old,facet:[host,'eth0']}] )));const snapshot=await new NewRelicTelemetryAdapter(config).getSnapshot(host);expect(snapshot.observations.some(item=>item.status==='STALE')).toBe(true);expect(snapshot.resource.status).toBe('warning')})
  it('keeps Tavily failure optional',async()=>{const unavailable:ResearchProvider={search:async()=>{throw new Error('offline')}};await expect(new OptionalResearchProvider(unavailable).search('storage docs')).resolves.toMatchObject({status:'RESEARCH_FAILED',sources:[]})})
})
