import { Link } from 'react-router-dom'
import { useAuthStatus } from 'deepspace'
import { ArrowRight, CheckCircle2, Eye, LockKeyhole, Radar, ScrollText, ShieldCheck, Zap } from 'lucide-react'
import './home.css'
const stages = [['Observe', 'New Relic supplies real infrastructure telemetry.'], ['Verify', 'AVMOS validates source, timestamp, freshness, and evidence.'], ['Reason', 'Grok produces a constrained proposal, never authorization.'], ['Policy', 'Deterministic rules evaluate scope, evidence, budgets, and provider eligibility.'], ['Execute', 'Only an approved protected provider may act.'], ['Audit', 'Every material decision and outcome is recorded.']]
export default function LandingPage() { const { isLoaded, isSignedIn } = useAuthStatus(); const consoleHref = isLoaded && isSignedIn ? '/dashboard' : '/sign-in?next=/dashboard'; return <main className="landing">
  <section className="landing-hero"><div className="landing-grid"/><p className="landing-eyebrow">GOVERNED AUTONOMOUS OPERATIONS</p><h1>Autonomous operations<br/>for critical infrastructure.</h1><p className="landing-lead">AVMOS connects real infrastructure telemetry to governed autonomous action—verifying conditions, reasoning over evidence, enforcing deterministic policy, and executing only approved operations.</p><div className="landing-actions"><Link className="landing-primary" to={consoleHref}>Open Console <ArrowRight size={17}/></Link><a className="landing-secondary" href="#how-it-works">How it works</a></div><p className="landing-trust"><ShieldCheck size={15}/> AI proposes. Policy authorizes. Protected providers execute.</p></section>
  <section className="landing-section landing-problem"><p className="landing-section-label">THE OPERATIONAL GAP</p><div><h2>Detection is only the beginning.</h2><p>Monitoring can identify rising storage, memory pressure, or degraded services. An operator still has to validate the signal, determine a response, check authority, execute safely, and verify the result. AVMOS governs that complete path.</p></div></section>
  <section id="how-it-works" className="landing-section"><p className="landing-section-label">HOW AVMOS WORKS</p><div className="landing-flow">{stages.map(([name, description], index) => <article key={name}><span>{String(index + 1).padStart(2,'0')}</span><h3>{name}</h3><p>{description}</p></article>)}</div></section>
  <section className="landing-section landing-boundary"><p className="landing-section-label">TRUST BY DESIGN</p><div className="landing-card"><LockKeyhole/><h3>Authority stays deterministic</h3><p>Models cannot change policy, reserve budgets, select arbitrary payment rails, or access execution secrets.</p></div><div className="landing-card"><Eye/><h3>Evidence stays visible</h3><p>Freshness, source state, policy checks, execution transitions, and audit outcomes remain inspectable.</p></div><div className="landing-card"><ScrollText/><h3>Outcomes stay auditable</h3><p>Approved, denied, failed, unknown, and reconciled outcomes are recorded without treating acceptance as success.</p></div></section>
  <section className="landing-section"><p className="landing-section-label">OPERATIONAL USE</p><div className="landing-examples"><article><Radar/><h3>Capacity</h3><p>Verify a rising storage trend before proposing a governed capacity action.</p></article><article><Zap/><h3>Procurement</h3><p>Validate vendor, currency, destination, transaction limits, and daily budget before settlement.</p></article><article><CheckCircle2/><h3>Incident response</h3><p>Move from trusted evidence to a controlled response with a continuous audit trail.</p></article></div></section>
  <section className="landing-cta"><div><p className="landing-section-label">AVMOS</p><h2>Reduce the time between detection and approved operational response.</h2></div><Link className="landing-primary" to={consoleHref}>Open Console <ArrowRight size={17}/></Link></section>
</main> }
