import type { ReactNode } from 'react'
import { Link } from 'react-router-dom'
export type ResourceRow = { hostname:string; type:string; status:string; telemetryStatus:string; telemetrySource:string; metrics: Record<string,number>; lastObservedAt:string; freshnessSeconds?:number }
export type CurrentMetric = { resourceId:string; metric:string; value?:number; unit:string; status:string; observedAt:string; freshnessMs:number }
export type AlertRow = { resourceId:string; metric:string; severity:string; status:string; value:number; threshold:number; openedAt:string; updatedAt:string; resolvedAt?:string }
export type AuditRow = { timestamp:string; actor:string; eventType:string; actionId:string; resourceId:string; policyVersion?:string; details:Record<string,unknown>; transactionHash?:string }
export type AggregateRow = { resourceId:string; metric:string; bucketStart:string; minimum:number; maximum:number; average:number; sampleCount:number; status:string }
export function ConsoleShell({ eyebrow, title, description, actions, children }:{ eyebrow:string; title:string; description:string; actions?:ReactNode; children:ReactNode }) { return <main className="console-page"><header className="console-heading"><div><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></div>{actions}</header>{children}</main> }
export function Panel({ title, detail, children, className='' }:{ title:string; detail?:string; children:ReactNode; className?:string }) { return <section className={`console-panel ${className}`}><header><h2>{title}</h2>{detail && <span>{detail}</span>}</header><div className="console-panel-body">{children}</div></section> }
export function StatusPill({ status }:{ status:string }) { return <span className={`status-pill status-${status.toLowerCase()}`}>{status}</span> }
export function Empty({ children }:{children:ReactNode}) { return <div className="console-empty">{children}</div> }
export function MetricValue({ metric }:{metric?:CurrentMetric}) { if (!metric || metric.value === undefined) return <span>—</span>; return <span>{metric.unit === 'percent' ? `${metric.value.toFixed(1)}%` : formatRate(metric.value)}</span> }
export function metricMap(records:Array<{data:CurrentMetric}>, resourceId:string) { return Object.fromEntries(records.filter((r)=>r.data.resourceId===resourceId).map((r)=>[r.data.metric,r.data])) as Record<string,CurrentMetric> }
export function ResourceTable({ resources, metrics }:{resources:Array<{recordId:string;data:ResourceRow}>;metrics:Array<{data:CurrentMetric}>}) { return <div className="table-scroll"><table className="console-table"><thead><tr><th>Resource</th><th>Status</th><th>CPU</th><th>Memory</th><th>Storage</th><th>Network</th><th>Last seen</th><th></th></tr></thead><tbody>{resources.map((row)=>{const m=metricMap(metrics,row.recordId);return <tr key={row.recordId}><td><strong>{row.data.hostname}</strong><small>{row.recordId}</small></td><td><StatusPill status={row.data.telemetryStatus}/></td><td><MetricValue metric={m.cpu_utilization}/></td><td><MetricValue metric={m.memory_utilization}/></td><td><MetricValue metric={m.storage_utilization}/></td><td><MetricValue metric={m.network_receive_bytes_per_second}/></td><td>{relative(row.data.lastObservedAt)}</td><td><Link to={`/resources/${encodeURIComponent(row.recordId)}`}>View →</Link></td></tr>})}</tbody></table></div> }
export function relative(value?:string) { if(!value||Number.isNaN(Date.parse(value))) return 'Unknown'; const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(value))/1000)); return seconds<60?`${seconds}s ago`:seconds<3600?`${Math.floor(seconds/60)}m ago`:`${Math.floor(seconds/3600)}h ago` }
function formatRate(value:number){return value>=1_000_000?`${(value/1_000_000).toFixed(1)} MB/s`:value>=1000?`${(value/1000).toFixed(1)} KB/s`:`${value.toFixed(0)} B/s`}
export function Sparkline({points}:{points:number[]}) { if(points.length<2)return <div className="spark-empty">No history</div>; const min=Math.min(...points),max=Math.max(...points),range=max-min||1; const path=points.map((v,i)=>`${i?'L':'M'} ${(i/(points.length-1))*100} ${36-((v-min)/range)*32}`).join(' ');return <svg className="sparkline" viewBox="0 0 100 40" preserveAspectRatio="none" aria-label="Metric history"><path d={path}/></svg> }
